/* INSERT D'UNE LIGNE DANS LA  TABLE_1*/

INSERT INTO TABLE_1 (ID, NOM, PRENOM, ACCESS_RIGHTS)
VALUES ('1','MARTIN','Franck',true);
INSERT INTO TABLE_1 (ID, NOM, PRENOM, ACCESS_RIGHTS)
VALUES ('2','DUPONT','RENE',true);
INSERT INTO TABLE_1 (ID, NOM, PRENOM, ACCESS_RIGHTS)
VALUES ('3','DURANT','Jacques',true);
INSERT INTO TABLE_1 (ID, NOM, PRENOM, ACCESS_RIGHTS)
VALUES ('4','DUPUIS','Hervé',true);

COMMIT;