/* UPDATE D'UNE LIGNE DANS LA  TABLE_1*/

UPDATE TABLE_1 SET ACCESS_RIGHTS = FALSE WHERE ID='1';
UPDATE TABLE_1 SET ACCESS_RIGHTS = TRUE WHERE ID='2';
UPDATE TABLE_1 SET ACCESS_RIGHTS = TRUE WHERE ID='3';
UPDATE TABLE_1 SET ACCESS_RIGHTS = FALSE WHERE ID='4';


COMMIT;